name: first-workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "hellow world"
      - name: print goodbye
        run: echo "hello done - bye"
